### ISSUE TITLE
controller::is_admin_or_manager() should check capabilities, not role names

### ISSUE THREAD

**Issue by mudrd8mz** [yogshirsath/moodle-local_disablerightclick#4]
The method `controller::is_admin_or_manager()` should not evaluate the user access like this.

Instead, the plugin should declare a capability like "Can use right click copy paste" or so. That capability would by default be granted to "manager" archetype only. Any user with that capability would be able to use these features normally without limits and it is up to the admin to decide (e.g. let teachers still use copy & paste which seems reasonable).

**Comment by yogshirsath** [comment]
Sure. I'll change it to capability.

**Comment by luiggisanso** [comment]
Hi

It would be great in order to add or remove this capability for students in quiz activity during an exam for example ;-)

Hope.

**Comment by luiggisanso** [comment]
Hi @yogshirsath 

Thanks for this plugin and modification it's better for my studiecase

But is it possible to add the module context ?

For the site (system) and course it's ok.
If it's "disable --> yes" (plugin settings) and "allowed" in the student role setting, student can use right clic.
And I can manage for a specific course from student permission to turn off the right clic.

But I'm looking for the possibility to have several quizzes (training) with all rights, and only one with this disable right click (exam).
Is it possible ?
