### ISSUE TITLE
[NOT AN ISSUE] Override plugin in login page

### ISSUE THREAD

**Issue by mardoqueo** [yogshirsath/moodle-local_disablerightclick#5]
Hello! Thanks for this extension!

Is there a way I could allow paste functionality only in the login page?

Thanks!

**Comment by semteacher** [comment]
+1
In addition - lot of themes have login dialog on frontpage. Would be fine to allow copy/paste for this case too

**Comment by yogshirsath** [comment]
Added this feature in https://github.com/yogshirsath/moodle-local_disablerightclick/commit/b0a9e7a23ac94e47564744d963316e07a9f82f6b.

**Comment by mardoqueo** [comment]
Thanks!
