### ISSUE TITLE
Please protect site's Iframe content also

### ISSUE THREAD

**Issue by jigeeshuvijayan** [yogshirsath/moodle-local_disablerightclick#7]
Hello! Thank you for this nice extension!
This plugin help me to protect my course content.But some cases I need to put my pdf, ppt or word document in google drive ... and paste embed it to my course as iframe. But Inside iframe all copy/paste rightclick etc is enabled.Please guide me to resolve this issue.

**Comment by semteacher** [comment]
+1 for such feature
