### ISSUE TITLE
Allow teachers to rightclick

### ISSUE THREAD

**Issue by stonerl** [yogshirsath/moodle-local_disablerightclick#9]
Would it be possible to add teachers and teachers without editing rights to the user that are allowed to right-click? Since they are the ones that fill the courses with content and sometimes need to right-click, to enter text/links etc.

Or maybe have 2 checkboxes. Where the 2 teacher roles could be added or removed from those who are allowed to right-click.

**Comment by yogshirsath** [comment]
I have used capability api to restrict users.
Just enable local/disablerightclick:allow capability to teacher and editing teacher.
They will get full access.

**Comment by stonerl** [comment]
Uh, I see. Thank you for the hint.
